name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev libsqlite3-dev

      - name: Build with make
        run: |
          make clean
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vbdist-linux
          path: bin/build/vbdist

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with make
        run: |
          make clean
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vbdist-win
          path: bin/build/vbdist.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: release/

      - name: Compress
        run: |
          cd release
          zip -r vbdist-linux.zip vbdist-linux
          zip -r vbdist-win.zip vbdist-win

      - name: List
        run: ls -l release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            release/vbdist-linux.zip
            release/vbdist-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
