name: Build

on:
  push:
    branches:
      - main
      - build
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev

      - name: Build with make
        run: |
          make clean
          make dep
          make build

      - name: Compress
        run: |
          cd bin/build
          tar -czvf vbdist-linux.tar.gz vbdist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vbdist-linux
          path: bin/build/vbdist-linux.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with make
        run: |
          make clean
          make dep
          make build

      - name: Compress
        run: |
          cd bin/build
          7z a vbdist-windows.zip vbdist.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vbdist-windows
          path: bin/build/vbdist-windows.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/

      - name: List
        run: ls -l release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            release/vbdist-linux/vbdist-linux.tar.gz
            release/vbdist-windows/vbdist-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
